--  Ada interface for TRNG (Cryptographic Co-Processor). Coded by Wojciech Lawren.

--  Copyright (C) 2020, Wojciech Lawren, All rights reserved.

--  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES,
--  INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
--  DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
--  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
--  SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
--  WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE
--  USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
pragma Ada_2022;
--  RDRAND RDSEED
package rdrand with
   Pure
is
   --  rdrand
   generic
      type rx is mod <>;
   function rand return rx with
      Pre  => rx'Size in 64 | 32 | 16,
      Post => rand'Result > 0,
      Inline;

   --  rdseed
   generic
      type sx is mod <>;
   function seed return sx with
      Pre  => sx'Size in 64 | 32 | 16,
      Post => seed'Result > 0,
      Inline;

end rdrand;
